@startuml
'https://plantuml.com/sequence-diagram

title Handing Archi Model between "master" and user's "working" branches

autonumber

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response


Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response

@enduml